import Head from "next/head";
import Hero from "../components/Hero";
import Post from "../components/Post";

const Blog = () => {
	return (
		<>
			<Head>
				<title>Kurverwaltung Göhren</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<Hero />

				<div className="container mx-auto my-16 grid grid-cols-1 tablet:grid-cols-2 laptop:grid-cols-3 gap-x-4 gap-y-16">
					<Post />
					<Post />
					<Post />
					<Post />
					<Post />
					<Post />
					<Post />
					<Post />
					<Post />
					<Post />
					<Post />
					<Post />
					<Post />
					<Post />
					<Post />
					<Post />
				</div>
			</main>
		</>
	);
};

export default Blog;
