import { useState } from "react";
import dynamic from "next/dynamic";
import Head from "next/head";
import AccomodationFilter from "../components/AccomodationFilter";
import AccomodationGrid from "../components/AccomodationGrid";
import ReviewSlider from "../components/ReviewSlider";
import TopicGrid from "../components/TopicGrid";
import TopicSlider from "../components/TopicSlider";

const Map = dynamic(() => import("../components/AccomodationMap"), { ssr: false });

export default function Gastgeber() {
	const [map, showMap] = useState(false);

	return (
		<>
			<Head>
				<title>Gastgeber - Kurverwaltung Göhren</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<AccomodationFilter toggleMap={() => showMap((state) => !state)} />
				{map ? <Map /> : <AccomodationGrid />}
				<ReviewSlider />
				<TopicSlider />
				<TopicGrid />
			</main>
		</>
	);
}
