import Head from "next/head";
import TopicSlider from "../components/TopicSlider";
import TopicGrid from "../components/TopicGrid";
import BlogTeaser from "../components/BlogTeaser";
import EventSLider from "../components/EventSlider";
import ReviewSlider from "../components/ReviewSlider";
import Hero from "../components/Hero";
import Grid from "../components/Grid";

export default function Home() {
	return (
		<>
			<Head>
				<title>Kurverwaltung Göhren</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				{/** Headerbanner */}
				<Hero />
				{/** Headerbanner End */}

				{/** Textcontent */}
				<div className="container mx-auto my-16">
					<div className="max-w-[800px]">
						<h2 className="text-2xl font-semibold mb-4">
							Erleben, Entspannen, Genießen oder Action? <br /> Natürlich im Ostseebad Göhren.
						</h2>
						<p>
							I am baby umami farm-to-table shoreditch leggings, crucifix VHS forage ennui small batch
							four dollar toast cray. Shaman gentrify live-edge DIY salvia, blog cardigan schlitz whatever
							la croix post-ironic art party gastropub. Taiyaki truffaut trust fund pitchfork, taxidermy
							disrupt kinfolk.
						</p>
					</div>
				</div>
				{/** Textcontent End */}

				{/** Grid */}
				<Grid />
				{/** Grid End */}

				{/** Events Slider */}
				<EventSLider />
				{/** Events Slider End */}

				{/** Reviews */}
				<ReviewSlider />

				{/** Reviews End */}

				{/** Thema Slider */}
				<TopicSlider />
				{/** Thema Slider End */}

				{/** Thema Grid */}
				<TopicGrid />
				{/** Thema Grid End */}

				{/** Blog Teaser */}
				<BlogTeaser />
				{/** Blog Teaser End */}
			</main>
		</>
	);
}
