import Head from "next/head";
import Link from "next/link";
import Hero from "../components/Hero";
import Grid from "../components/Grid";
import Banner from "../components/Banner";

const Kurort = () => {
	return (
		<>
			<Head>
				<title>Kurverwaltung Göhren</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<Banner />

				<div className="container mx-auto my-16">
					<ul className="flex items-center gap-2 text-sm text-slate-400">
						<li>
							<Link href="/">Startseite</Link>
						</li>
						<li>
							<span>-</span>
						</li>
						<li>
							<Link href="/erleben">Erleben</Link>
						</li>
						<li>
							<span>-</span>
						</li>
						<li>
							<Link href="/">Kurort</Link>
						</li>
					</ul>

					<div className="grid grid-cols-1 laptop:grid-cols-2 mt-8">
						<div className="col-span-1">
							<h1 className="text-bigger">Bezaubernde und einzigartige Naturerlebnisse</h1>
						</div>
						<div className="col-span-1">
							<p>
								Die wunderschöne und vielfältige Natur der Insel Rügen ist gleichzeitig auch ihr
								Reichtum. Hier bieten sich Ihnen viele Möglichkeiten, die Natur aktiv oder einfach nur
								genießend zu erleben, sie dabei aber nicht zu zerstören. Ganz im Gegenteil, bei uns
								können Sie die Natur erleben und gleichzeitig aktiv zum Umweltschutz beitragen! Und das
								gilt auch schon für die Kleinsten!{" "}
							</p>
						</div>
					</div>
				</div>

				<div className="container mx-auto">
					<div className="grid grid-cols-1 laptop:grid-cols-3 gap-4">
						<div className="col-span-1 laptop:col-span-2 bg-slate-100 p-8">
							<h2 className="text-big">Offizielles Prädikat "Kneippkurort"</h2>
							<p className="my-4">
								Seit dem 03. Mai des Jahres 2007 trägt das Ostseebad Göhren das offizielle Prädikat
								"Kneippkurort". An vielen Stellen von Göhren finden Sie Hinweise darauf. Und dies mit
								Recht, denn die 5 Säulen der Kneippschen Lehre sind: - Die Heilwirkung des Wassers - Die
								therapeutische Wirkung von Bewegung an frischer Luft - Die milde Wirkung von
								Heilpflanzen - Eine gesunde und ausgewogene Ernährung - Der sinnvolle Wechsel zwischen
								Anspannung und Entspannung Die außergewöhnlich guten klimatischen Bedingungen, mit dem
								milden Reizklima, den positiven Eigenschaften einer intakten Natur mit Laub- und
								Nadelhölzern sowie zwei traumhaften Stränden sorgen für einen erholsamen und
								entspannenden Aufenthalt inmitten des Biosphärenreservats Südost-Rügen. Dazu kommt eine
								Infrastruktur, die viel zu bieten hat für Ihre Gesundheit: Hervorragend ausgestattete
								Kur- und Wellnesseinrichtungen, die den höchsten Standards entsprechen. Der Kurpark und
								der Kurplatz mit vielen Möglichkeiten zum Verweilen laden ein zum Entspannen und auch
								zum Erleben von kulturellen Höhepunkten. Im Kneippgarten bieten beipielsweise ein
								Wassertretbecken, ein Armbadbecken und vieles mehr die Möglichkeit, die Elemente der
								Kneippschen Lehre in unmittelbarer Nähe zum feinsandigen Ostseestrand zu erleben. Seit
								2013 gehört Göhren zu den Kneipp-Premium-Class-Orten. Besonders stolz ist das Ostseebad
								auf seinen Kindergarten, der seit 2004 offiziell vom Kneipp-Bund als Kneipp-Kindergarten
								anerkannt ist.
							</p>
							<p className="my-4">
								Sich rundum wohlzufühlen, gesund zu leben und hierfür insbesondere präventiv zu handeln
								ist für viele Menschen seit einigen Jahren zunehmend bedeutsam geworden. Dies ist im
								letzten Jahr aus den bekannten Gründen noch einmal mehr in den Vordergrund gerückt.
								Deshalb ist es äußerst passend, dass 2021 bundesweit zum „Kneipp-Jahr“ berufen wurde.
								Anlässlich des 200. Geburtstags von Sebastian Kneipp wird seiner bewährten
								Gesundheitsphilosophie, die aufgrund ihrer ganzheitlichen Ausrichtung moderner denn je
								ist, gedacht und die vielfältigen, oft einfachen Anwendungen sind gezeigt worden.
							</p>
						</div>
						<div className="col-span-1 grid grid-cols-1 h-full gap-4">
							<div className="col-span-1 h-full bg-slate-200 flex flex-col justify-end">
								<div className="bg-gradient-to-t from-neutral-400 text-white p-8">
									<h3 className="font-semibold">Kneipkurort</h3>
									<p>Gesundheit per Prädikat</p>
								</div>
							</div>
							<div className="col-span-1 h-full bg-slate-200 flex flex-col justify-end">
								<div className="bg-gradient-to-t from-neutral-400 text-white p-8">
									<h3 className="font-semibold">Kneipkurort</h3>
									<p>Gesundheit per Prädikat</p>
								</div>
							</div>
						</div>
					</div>
				</div>

				<div className="container mx-auto grid grid-cols-1 tablet:grid-cols-2 laptop:grid-cols-4 gap-x-4 gap-y-16 my-16">
					<div className="col-span-1 flex flex-col justify-between">
						<h2 className="text-big">Kuranwendungen & Anbieter</h2>

						<div>
							<p>
								Denn im Ostseebad finden sich vielfältige Möglichkeiten, die zu einem Kuraufenthalt
								einladen. Zur Behandlung werden die positiven Wirkfaktoren des Klimas und des Meeres
								genutzt.
							</p>

							<ul className="mt-8">
								<li>
									<Link href="/">
										<a className="flex items-center gap-2 group font-medium">
											<span>Häufig gestellte Fragen</span>
											<span>
												<svg
													width="20"
													height="10"
													viewBox="0 0 20 10"
													fill="none"
													xmlns="http://www.w3.org/2000/svg"
													className="block group-hover:translate-x-4"
												>
													<path
														d="M19 5H1M15 1L19 5L15 1ZM19 5L15 9L19 5Z"
														stroke="black"
														strokeWidth="2"
														strokeLinecap="round"
														strokeLinejoin="round"
													/>
												</svg>
											</span>
										</a>
									</Link>
								</li>
								<li>
									<Link href="/">
										<a className="flex items-center gap-2 group font-medium">
											<span>alle Angebote</span>
											<span>
												<svg
													width="20"
													height="10"
													viewBox="0 0 20 10"
													fill="none"
													xmlns="http://www.w3.org/2000/svg"
													className="block group-hover:translate-x-4"
												>
													<path
														d="M19 5H1M15 1L19 5L15 1ZM19 5L15 9L19 5Z"
														stroke="black"
														strokeWidth="2"
														strokeLinecap="round"
														strokeLinejoin="round"
													/>
												</svg>
											</span>
										</a>
									</Link>
								</li>
							</ul>
						</div>
					</div>

					<div className="col-span-1">
						<Link href="/">
							<a>
								<img src="" alt="" className="w-full bg-slate-200 aspect-portrait" />
								<h2 className="mt-4 font-medium">Waldhotel Göhren</h2>
							</a>
						</Link>
					</div>
					<div className="col-span-1">
						<Link href="/">
							<a>
								<img src="" alt="" className="w-full bg-slate-200 aspect-portrait" />
								<h2 className="mt-4 font-medium">Waldhotel Göhren</h2>
							</a>
						</Link>
					</div>
					<div className="col-span-1">
						<Link href="/">
							<a>
								<img src="" alt="" className="w-full bg-slate-200 aspect-portrait" />
								<h2 className="mt-4 font-medium">Waldhotel Göhren</h2>
							</a>
						</Link>
					</div>
				</div>
			</main>
		</>
	);
};

export default Kurort;
