import Head from "next/head";
import ReviewSlider from "../components/ReviewSlider";
import TopicGrid from "../components/TopicGrid";
import TopicSlider from "../components/TopicSlider";
import Event from "../components/Event";
import EventFilter from "../components/Eventfilter";

export default function Veranstaltungen() {
	return (
		<>
			<Head>
				<title>Veranstaltungen - Kurverwaltung Göhren</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<EventFilter />
			<main>
				<div className="container mx-auto grid grid-cols-1 tablet:grid-cols-2 laptop:grid-cols-4 gap-x-4 gap-y-16 mt-8">
					<Event />
					<Event />
					<Event />
					<Event />
					<Event />
					<Event />
					<Event />
					<Event />
					<Event />
					<Event />
					<Event />
					<Event />
					<Event />
					<Event />
					<Event />
					<Event />
					<Event />
					<Event />
				</div>
				<ReviewSlider />
				<TopicSlider />
				<TopicGrid />
			</main>
		</>
	);
}
